// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcwnEbfK91l49X6SjcczXEQcGj7eKKqjw',
    appId: '1:442045475559:android:c089ba8559c7bc3ca81042',
    messagingSenderId: '442045475559',
    projectId: 'flutter-chat-c0b8c',
    storageBucket: 'flutter-chat-c0b8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNDdJMF_sO-QKzTi_BohmJrdirM2ZqKLs',
    appId: '1:442045475559:ios:d613d43cb9d92e1aa81042',
    messagingSenderId: '442045475559',
    projectId: 'flutter-chat-c0b8c',
    storageBucket: 'flutter-chat-c0b8c.appspot.com',
    androidClientId: '442045475559-1sh4el4kb1b7n804i9ckjqbvnhouep7m.apps.googleusercontent.com',
    iosClientId: '442045475559-0mq5ukerr3hvjussoi9lbgtpciv24ac1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );
}
